### ISSUE TITLE
[Question]: Why is Kafka needed in the Gateway Service

### ISSUE THREAD

**Issue by juliuskrah** [Prempeh-Gyan/1.4-Gateway-Service#1]
I understand Kafka is a messaging store to reliably deliver messages between different services.
In more recent times people have started using it for _stream processing_ and _log aggregation_. 

My question is why is it needed in the gateway service as this service mainly serves as an edge router or performs API aggregation when needed.

**Comment by Prempeh-Gyan** [comment]
@juliuskrah you are absolutely right about Kafka, the reason why I included it in this flow is to demonstrate how you can use Kafka at the Gateway level to decouple the microservices from process demands. 

So for a very simple example, if you have say 5 microservices with processing capacity of say 10 requests per minute, running behind an API Gateway, then naturally in microservices architecture when the average request exceeds the processing capacity, you would have to scale up to handle the demand.

If for some reason you do not want to scale up in situations like this, then one could use Kafka to build up the requests in a queue until the services catch up with the waiting requests.

Another benefit is that, in certain situations as end users send in requests to the Gateway, if the intended service is down, the system loses the data from that request, to avoid this (given that the use case fits this solution) one could again queue up these requests while a new instance of the intended service is brought up to process them. In this way although there was a downtime, no data would be lost. 

But again the use case must make sense in order to use this kind of fallback solution.

**Comment by juliuskrah** [comment]
Thank you for such a breakdown. I didn't know Kafka could be used this way.

How is it being applied in your sample, I see the Kafka configuration in
the Config Server but I don't see its implementation in the source code.
